# 파이토치(PyTorch)

<img src="https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbuUgoV%2FbtqwWZvcHHX%2Fd6XzIFBEfiuFb0UvyV4A50%2Fimg.jpg" width="300">

- 코드 출처: https://pytorch.org/tutorials/

## 파이토치의 구성요소

- `torch`: 텐서를 생성하는 라이브러리

- `torch.autograd`: 자동미분 기능을 제공하는 라이브러리

- `torch.nn`: 신경망을 생성하는 라이브러리

- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리

- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공

- `torch.legacy`(./nn/.optim): Torch로부터 포팅해온 코드

- `torch.onnx`: ONNX(Open Neural Network Exchange)

  - 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)
- 넘파이(NumPy)의 ndarray와 유사

- GPU를 사용한 연산 가속도 가능

In [6]:
import torch

In [3]:
torch.__version__

'1.7.1'

### 초기화 되지 않은 행렬 

In [7]:
x = torch.empty(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### 무작위로 초기화된 행렬

In [8]:
x = torch.rand(4, 2)
print(x)

tensor([[0.1090, 0.0010],
        [0.6156, 0.7250],
        [0.6002, 0.0523],
        [0.4820, 0.2469]])


### dtype이 long, 0으로 채워진 텐서

In [10]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [11]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [12]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [13]:
x = torch.randn_like(x, dtype=torch.float) # x 모양은 그대로 가져오되, 랜덤으로 채움
print(x)

tensor([[ 1.6501,  0.3065,  1.1234,  0.9832],
        [ 1.1522, -1.9466, -0.9025, -0.7178]])


### 텐서의 크기

In [15]:
print(x.size())

torch.Size([2, 4])


## 텐서의 연산(operations)

### 덧셈 1

In [16]:
print(x)

tensor([[ 1.6501,  0.3065,  1.1234,  0.9832],
        [ 1.1522, -1.9466, -0.9025, -0.7178]])


In [18]:
y = torch.rand(2, 4)
print(y)
print(x + y)

tensor([[0.6910, 0.0615, 0.0724, 0.7658],
        [0.9685, 0.5029, 0.4000, 0.0319]])
tensor([[ 2.3412,  0.3680,  1.1958,  1.7490],
        [ 2.1207, -1.4438, -0.5025, -0.6859]])


### 덧셈2

In [19]:
print(torch.add(x, y))

tensor([[ 2.3412,  0.3680,  1.1958,  1.7490],
        [ 2.1207, -1.4438, -0.5025, -0.6859]])


### 덧셈3
- 결과 텐서를 인자로 제공

In [20]:
result = torch.empty(2, 4)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.3412,  0.3680,  1.1958,  1.7490],
        [ 2.1207, -1.4438, -0.5025, -0.6859]])


### 덧셈4
- `in-place` 방식

- (참고) in-place 방식
  - in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
  - `x.copy_(y), x.t_()`

In [21]:
print(x)
print(y)
y.add_(x) # y += x
print(y)

tensor([[ 1.6501,  0.3065,  1.1234,  0.9832],
        [ 1.1522, -1.9466, -0.9025, -0.7178]])
tensor([[0.6910, 0.0615, 0.0724, 0.7658],
        [0.9685, 0.5029, 0.4000, 0.0319]])
tensor([[ 2.3412,  0.3680,  1.1958,  1.7490],
        [ 2.1207, -1.4438, -0.5025, -0.6859]])


### 그 외의 연산
- `torch.sub` : 뺄셈

- `torch.mul` : 곱셉

- `torch.div` : 나눗셈

- `torch.mm` : 내적(dot product)

In [22]:
x = torch.Tensor([[1,2],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[-1., -2.],
        [-1., -1.]])
tensor([[-1., -2.],
        [-1., -1.]])
tensor([[-1., -2.],
        [-1., -1.]])


In [23]:
x = torch.Tensor([[1,2],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([[ 2.,  8.],
        [30., 56.]])
tensor([[ 2.,  8.],
        [30., 56.]])
tensor([[ 2.,  8.],
        [30., 56.]])


In [24]:
x = torch.Tensor([[1,2],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([[0.5000, 0.5000],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.5000],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.5000],
        [0.8333, 0.8750]])


In [26]:
# 행렬 곱

x = torch.Tensor([[1, 3],
                  [5, 7]])
y = torch.Tensor([[2, 4],
                  [6, 8]])
print(torch.mm(x, y))

tensor([[20., 28.],
        [52., 76.]])


## 텐서의 조작(manipulations)

### 인덱싱
- 넘파이처럼 인덱싱 사용가능

In [27]:
print(x)

tensor([[1., 3.],
        [5., 7.]])


In [28]:
print(x[:, 1])

tensor([3., 7.])


### view
- 텐서의 크기(size)나 모양(shape)을 변경

In [30]:
x = torch.randn(4, 5)
y = x.view(20)
z = x.view(5, -1)

print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 5])
torch.Size([20])
torch.Size([5, 4])


### item
- 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음


In [31]:
x = torch.randn(1)
print(x)
print(x.item()) # item은 실제 존재하는 값을 출력
print(x.dtype)

tensor([-1.2442])
-1.2442466020584106
torch.float32


- 스칼라값 하나만 존재해야함

In [32]:
x = torch.randn(2)
print(x)
print(x.item())
print(x.dtype)

tensor([ 0.6505, -0.1692])


ValueError: only one element tensors can be converted to Python scalars

### squeeze 
- 차원을 축소(제거)

In [35]:
tensor = torch.rand(1, 3, 3)
tensor.shape

torch.Size([1, 3, 3])

In [37]:
t = tensor.squeeze()

print(t)
print(t.shape)

tensor([[0.8923, 0.4276, 0.5339],
        [0.6165, 0.0292, 0.5612],
        [0.8561, 0.4718, 0.9373]])
torch.Size([3, 3])


### unsqueeze
- 차원을 증가(생성)

In [38]:
tensor = torch.rand(1, 3, 3)
print(tensor)
print(tensor.shape)

tensor([[[0.5565, 0.6312, 0.7997],
         [0.9269, 0.9845, 0.1968],
         [0.8369, 0.4552, 0.1705]]])
torch.Size([1, 3, 3])


In [39]:
t = tensor.unsqueeze(dim=0)

print(t)
print(t.shape)

tensor([[[[0.5565, 0.6312, 0.7997],
          [0.9269, 0.9845, 0.1968],
          [0.8369, 0.4552, 0.1705]]]])
torch.Size([1, 1, 3, 3])


### stack
- 텐서간 결합

In [41]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### cat
- 텐서를 결합하는 메소드(concatenate)

- 넘파이의 `stack`과 유사하지만, 쌓을 dim이 존재해야함
  - 예를 들어, 해당 차원을 늘려준 후 결합


In [42]:
a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a, b), dim=0)

print(c)
print(c.size())

tensor([[[[-0.0471,  0.6941, -0.2917],
          [-0.9304,  1.6389,  0.4841],
          [-1.1493, -0.4400, -1.3779]]],


        [[[-0.1711,  0.9311, -1.2980],
          [-0.7112, -0.4041, -1.6974],
          [ 1.0733, -0.0495, -0.5738]]]])
torch.Size([2, 1, 3, 3])


In [44]:
a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a, b), dim=0)

print(c)
print(c.size())

tensor([[[[ 0.7838, -0.7423, -0.7135],
          [ 0.2172, -0.0148,  0.3422],
          [ 0.9447, -0.4208,  0.9655]]],


        [[[ 0.0730,  0.2941,  0.1313],
          [-0.5997, -0.8293, -0.3959],
          [ 1.6261,  2.5337,  1.6468]]]])
torch.Size([2, 1, 3, 3])


In [45]:
a = torch.randn(1, 3, 3)
b = torch.randn(1, 3, 3)
c = torch.cat((a, b), dim=1)

print(c)
print(c.size())

tensor([[[ 0.4672,  1.1678,  1.7082],
         [ 0.8964,  0.0439,  0.0685],
         [ 2.5033,  0.0252,  0.9225],
         [-1.7642,  0.8292,  0.0251],
         [ 0.6956,  0.2751,  0.3485],
         [-0.3368, -0.7318, -0.6451]]])
torch.Size([1, 6, 3])


### chuck
- 텐서를 여러 개로 나눌 때 사용

- 몇 개의 텐서로 나눌 것이냐

In [46]:
tensor = torch.rand(3, 6)
t1, t2, t3 = torch.chunk(tensor, 3, dim=1)

print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.4137, 0.6698, 0.2672, 0.0333, 0.6030, 0.5976],
        [0.7353, 0.5931, 0.1429, 0.0316, 0.2058, 0.6058],
        [0.8921, 0.9462, 0.7161, 0.0617, 0.7281, 0.6648]])
tensor([[0.4137, 0.6698],
        [0.7353, 0.5931],
        [0.8921, 0.9462]])
tensor([[0.2672, 0.0333],
        [0.1429, 0.0316],
        [0.7161, 0.0617]])
tensor([[0.6030, 0.5976],
        [0.2058, 0.6058],
        [0.7281, 0.6648]])


### split
- `chunck`와 동일한 기능이지만 조금 다름

- 하나의 텐서당 크기가 얼마이냐

### torch ↔ numpy
- Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능

  - `numpy()`
  - `from_numpy()`

- (참고)
  - Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

## CUDA Tensors
- `.to` 메소드를 사용하여 텐서를 어떠한 장치로도 옮길 수 있음
  - 예) cpu, gpu

## AUTOGRAD (자동미분)
- autograd 패키지는 Tensor의 모든 연산에 대해 **자동 미분** 제공

- 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻

- backprop를 위한 미분값을 자동으로 계산

### Tensor

- data: tensor형태의 데이터

- grad: data가 겨쳐온 layer에 대한 미분값 저장

- grad_fn: 미분값을 계산한 함수에 대한 정보 저장 (어떤 함수에 대해서 backprop 했는지)

- `requires_grad` 속성을 `True`로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

- 계산이 완료된 후, `.backward()`를 호출하면 자동으로 `gradient`를 계산할 수 있으며, `.grad` 속성에 누적됨

- 기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

- 기록을 추적하는 것을 방지하기 위해 코드 블럭을 `with torch.no_grad():`로 감싸면 `gradient`는 필요없지만, `requires_grad=True`로 설정되어 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용

- Autograd 구현에서 매우 중요한 클래스 : `Function` 클래스

- `requires_grad_(...)`는 기존 텐서의 `requires_grad`값을 바꿔치기(`in-place`)하여 변경

### 기울기(Gradient)
- 역전파: `.backward()`를 통해 역전파 계산 가능

- `with torch.no_grad()`를 사용하여 gradient의 업데이트를 하지 않음

- `detach()`: 내용물(content)은 같지만 require_grad가 다른 새로운 Tensor를 가져올 때

### 자동 미분 흐름 다시 보기(1)
- 계산 흐름  
  $a \rightarrow b  \rightarrow c  \rightarrow out $

<br>

## $\quad \frac{\partial out}{\partial a} = ?$
- `backward()`를 통해  
  $a \leftarrow b  \leftarrow c  \leftarrow out $을 계산하면  
    $\frac{\partial out}{\partial a}$값이 `a.grad`에 채워짐


- $b = a + 2$

- $c = b^2$ 

- a의 `grad_fn`이 None인 이유  
  직접적으로 계산한 부분이 없었기 때문

### 자동 미분 흐름 다시 보기(2)
- `grad`값을 넣어서 `backward`

- 아래의 코드에서 `.grad`값이 None은 gradient값이 필요하지 않기 때문

## nn & nn.functional

- 두 패키지가 같은 기능이지만 방식이 조금 다름

- 위의 `autograd` 관련 작업들을 두 패키지를 통해 진행할 수 있음

- 텐서를 직접 다룰 때 `requires_grad`와 같은 방식으로 진행할 수 있음

- 결론적으로, `torch.nn`은 attribute를 활용해 state를 저장하고 활용하고,  
  `torch.nn.functional`로 구현한 함수의 경우에는 인스턴스화 시킬 필요 없이 사용이 가능
 


### nn 패키지

- 주로 가중치(weights), 편향(bias)값들이 내부에서 자동으로 생성되는 레이어들을 사용할 때  
  - 따라서, `weight`값들을 직접 선언 안함

- 예시
  - Containers

  - Convolution Layers

  - Pooling layers

  - Padding Layers

  - Non-linear Activations (weighted sum, nonlinearity)

  - Non-linear Activations (other)

  - Normalization Layers

  - Recurrent Layers

  - Transformer Layers

  - Linear Layers

  - Dropout Layers

  - Sparse Layers

  - Distance Functions

  - Loss Functions

  - ..
- https://pytorch.org/docs/stable/nn.html



- Convolution Layer 예시 (1)


### nn.functional 패키지

- 가중치를 직접 선언하여 인자로 넣어줘야함

- 예시)
  - Convolution functions

  - Pooling functions
  
  - Non-linear activation functions

  - Normalization functions

  - Linear functions

  - Dropout functions
  
  - Sparse functions
  
  - Distance functions

  - Loss functions
  - ..

- https://pytorch.org/docs/stable/nn.functional.html

- Convolution Layer 예시 (2)

## Torchvision

- `transforms`: 전처리할 때 사용하는 메소드

- `transforms`에서 제공하는 클래스 이외에  
  일반적으로 클래스를 따로 만들어 전처리 단계를 진행
  
  - 아래의 코드에서 다양한 전처리 기술 확인  
    https://pytorch.org/docs/stable/torchvision/transforms.html


- 예시)
  - `DataLoader`의 인자로 들어갈 `transform`을 미리 정의할 수 있음

  - `Compose`를 통해 리스트 안에 순서대로 전처리 진행

  - 대표적인 예로, `ToTensor`()를 하는 이유는  
   <u>torchvision이 PIL Image형태로만 입력을 받기 때문에</u> 데이터 처리를 위해서 Tensor형으로 변환해야함

## utils.data

- `Dataset`에는 다양한 데이터셋이 존재  
  - MNIST, CIFAR10, ...

- `DataLoader`, `Dataset`을 통해  
  `batch_size`, `train`여부, `transform`등을 인자로 넣어 데이터를 어떻게 load할 것인지 정해줄 수 있음

- `batch_size`만큼 데이터를 하나씩 가져옴

<u>**(중요) torch에서는 channel(채널)이 앞에 옴**</u>

- `channel first`

- tensorflow, keras 등에서는 channel이 뒤에 옴(`channel last`)

### 데이터 확인

## 각 Layer 설명

### nn.Conv2d

- `in_channels`: channel의 갯수

- `out_channels`: 출력 채널의 갯수

- `kernel_size`: 커널(필터) 사이즈

- 텐서플로우, 케라스와 다르게 레이어의 `input`인자에도 값을 집어 넣어줘야함

- `wegiht`확인

- `weight`는 `detach()`를 통해 꺼내줘야 `numpy()`변환이 가능

### Pooling
- `F.max_pool2d` 
  - `stride`

  - `kernel_size`

- `torch.nn.MaxPool2d` 도 많이 사용

- MaxPool Layer는 weight가 없기 때문에 바로 `numpy()`변환 가능

### Linear
- 1d만 가능 `.view()`를 통해 1D로 펼쳐줘야함

### Softmax

### F.relu

- ReLU 함수를 적용하는 레이어

- `nn.ReLU`로도 사용 가능

## Optimizer

- `import torch.optim as optim`

- `model`의 파라미터를 업데이트

- 예시)
  ```python
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
  optimizer = optim.SGD(model.parameters(), lr=0.001)
  ```

- `.zero_grad()`로 초기화
- `.step()`으로 업데이트

